import React, { useRef, useState } from 'react';
import { SessionData } from '../types';
import { toPng } from 'html-to-image';
import { Copy, Check, Image as ImageIcon, Bomb, Pencil, FileJson, ChevronDown, ChevronUp, Users, Rocket } from 'lucide-react';
import { DataPanel } from './DataPanel';

interface SatelliteGridProps {
  satellites: SessionData[];
  onExplode: (id: string) => void;
  onEdit: (id: string) => void;
  onImport: (data: SessionData[]) => void;
}

export const SatelliteGrid: React.FC<SatelliteGridProps> = ({ satellites, onExplode, onEdit, onImport }) => {
  const gridRef = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [showDataPanel, setShowDataPanel] = useState(false);

  const handleCopyText = () => {
    let textOutput = "=== 成都秘密基地TRPG俱乐部 卫星观测站 ===\n\n";
    // Filter out exploded sessions
    const activeSatellites = satellites.filter(s => !s.isExploded);
    
    if (activeSatellites.length > 0) {
        activeSatellites.forEach(s => {
             // 格式：房间号（人数情况）——时间||模组名||规则||主持人（联系方式）
             // 卫星团的时间通常是日期+时间文本
             textOutput += `${s.roomId}（${s.currentPlayers}/${s.maxPlayers}）——${s.date} ${s.startTime}||${s.moduleName}||${s.ruleSystem}||${s.gmName}（${s.gmContact}）\n`;
        });
    } else {
        textOutput += "暂无卫星观测记录。\n";
    }
    textOutput += "Generated by 不咕鸟 CardGen";
    navigator.clipboard.writeText(textOutput);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadImage = async () => {
    if (gridRef.current) {
        setSelectedId(null);
        setIsGenerating(true);
        try {
            await new Promise(r => setTimeout(r, 100));
            const dataUrl = await toPng(gridRef.current, { 
                cacheBust: true, 
                pixelRatio: 2, 
                backgroundColor: '#f0f9ff', // light sky blue background
                fetchRequestInit: { mode: 'cors' }
            });
            const link = document.createElement('a');
            link.download = `trpg-satellites.png`;
            link.href = dataUrl;
            link.click();
        } catch (err) {
            console.error(err);
            alert('生成图片失败，请重试');
        } finally {
            setIsGenerating(false);
        }
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
        {/* Toolbar */}
        <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-200 flex flex-wrap items-center justify-between gap-4 sticky top-20 z-30">
            <div className="flex gap-3">
                <button onClick={handleDownloadImage} disabled={isGenerating} className="btn-primary flex items-center gap-2 px-4 py-2 bg-sky-600 text-white rounded-lg font-bold hover:bg-sky-700 transition shadow-sm disabled:opacity-50">
                    {isGenerating ? <span className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full"/> : <ImageIcon size={18} />}
                    下载长图
                </button>
                <button onClick={handleCopyText} className="flex items-center gap-2 px-4 py-2 bg-white text-slate-700 border border-slate-300 rounded-lg font-bold hover:bg-slate-50 transition shadow-sm">
                    {copied ? <Check size={18} className="text-green-500" /> : <Copy size={18} />}
                    {copied ? '已复制' : '复制文本'}
                </button>
            </div>
            <button onClick={() => setShowDataPanel(!showDataPanel)} className="flex items-center gap-2 text-slate-500 hover:text-slate-800 font-medium text-sm transition">
                <FileJson size={18} />
                数据管理
                {showDataPanel ? <ChevronUp size={16}/> : <ChevronDown size={16}/>}
            </button>
        </div>

        {/* Data Panel */}
        {showDataPanel && (
            <DataPanel 
                data={satellites}
                onImport={onImport}
                onClose={() => setShowDataPanel(false)}
            />
        )}

        {/* Main Grid Content */}
        <div className="overflow-hidden rounded-2xl border border-sky-100 bg-sky-50 shadow-inner" onClick={() => setSelectedId(null)}>
            <div ref={gridRef} className="bg-sky-50 min-h-[600px] p-8">
                {/* Header */}
                <div className="flex items-center gap-3 mb-8 border-b-2 border-sky-200 pb-4">
                    <div className="bg-sky-600 p-2 rounded-lg shadow-lg rotate-3">
                        <Rocket size={32} className="text-white"/>
                    </div>
                    <div>
                        <h2 className="text-3xl font-black text-sky-900 tracking-wider">卫星观测站</h2>
                        <p className="text-sky-600 font-bold text-sm">SATELLITE STATION / TBA SESSIONS</p>
                    </div>
                    <div className="ml-auto text-right">
                         <div className="text-4xl font-black text-sky-200">{satellites.length}</div>
                         <div className="text-xs font-bold text-sky-400 uppercase">Pending</div>
                    </div>
                </div>

                {satellites.length === 0 ? (
                    <div className="flex flex-col items-center justify-center py-20 text-sky-300">
                        <Rocket size={64} className="mb-4 opacity-50"/>
                        <p className="text-xl font-bold">暂无观测数据</p>
                        <p className="text-sm">在制卡时选择“卫星”状态即可添加至此</p>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                        {satellites.map(s => (
                            <div 
                                key={s.id} 
                                onClick={(e) => { e.stopPropagation(); setSelectedId(selectedId === s.id ? null : s.id); }}
                                className={`
                                    bg-white rounded-xl p-4 border-2 transition-all cursor-pointer shadow-sm relative group
                                    ${selectedId === s.id ? 'border-indigo-500 ring-4 ring-indigo-100/50 z-10 scale-[1.02]' : 'border-sky-100 hover:border-sky-300 hover:shadow-md'}
                                    ${s.isExploded ? 'grayscale opacity-75 bg-slate-50' : ''}
                                `}
                            >
                                {/* Actions Overlay */}
                                {selectedId === s.id && (
                                    <div className="absolute -top-3 -right-3 flex gap-2 z-20 animate-in zoom-in duration-200">
                                        <button 
                                            onClick={(e) => { e.stopPropagation(); onExplode(s.id); setSelectedId(null); }} 
                                            className={`w-9 h-9 rounded-full flex items-center justify-center text-white shadow-lg border-2 border-white ${s.isExploded ? 'bg-slate-500' : 'bg-red-500 hover:bg-red-600'}`}
                                            title={s.isExploded ? "恢复" : "炸团"}
                                        >
                                            <Bomb size={16}/>
                                        </button>
                                        <button 
                                            onClick={(e) => { e.stopPropagation(); onEdit(s.id); setSelectedId(null); }} 
                                            className="w-9 h-9 rounded-full bg-indigo-600 hover:bg-indigo-700 text-white flex items-center justify-center shadow-lg border-2 border-white"
                                            title="编辑"
                                        >
                                            <Pencil size={16}/>
                                        </button>
                                    </div>
                                )}

                                {/* Status Badge */}
                                <div className="flex justify-between items-start mb-3">
                                    <span className={`text-[10px] font-bold px-2 py-1 rounded text-white ${s.sessionType === '商团' ? 'bg-amber-500' : s.sessionType === '活动团' ? 'bg-pink-500' : 'bg-indigo-500'}`}>
                                        {s.sessionType}
                                    </span>
                                    {s.isExploded ? (
                                        <span className="text-[10px] font-black text-slate-500 bg-slate-200 px-2 py-1 rounded">已炸团</span>
                                    ) : (
                                        <span className="text-[10px] font-bold text-sky-600 bg-sky-100 px-2 py-1 rounded border border-sky-200">
                                            {s.status}
                                        </span>
                                    )}
                                </div>

                                {/* Content */}
                                <div className={s.isExploded ? 'line-through opacity-60' : ''}>
                                    <h3 className="font-bold text-slate-900 text-lg leading-tight mb-1">{s.moduleName}</h3>
                                    <div className="text-xs font-bold text-sky-600 uppercase mb-3">{s.ruleSystem}</div>
                                    
                                    <div className="bg-slate-50 rounded-lg p-3 space-y-2 border border-slate-100">
                                        <div className="flex flex-col gap-0.5 text-xs">
                                            <div className="flex items-center gap-2">
                                                <span className="font-bold text-slate-400 w-8">GM</span>
                                                <span className="font-bold text-slate-700 truncate">{s.gmName}</span>
                                            </div>
                                            <div className="flex items-center gap-2">
                                                <span className="w-8"></span>
                                                <span className="text-[10px] text-slate-500 truncate">{s.gmContact}</span>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-2 text-xs">
                                            <span className="font-bold text-slate-400 w-8">时间</span>
                                            <span className="font-medium text-slate-700 truncate">{s.date} {s.startTime}</span>
                                        </div>
                                        <div className="flex items-center gap-2 text-xs">
                                            <span className="font-bold text-slate-400 w-8">人数</span>
                                            <div className="flex items-center gap-1">
                                                <Users size={12} className="text-slate-400"/>
                                                <span className="font-mono font-bold">{s.currentPlayers}/{s.maxPlayers}</span>
                                            </div>
                                        </div>
                                    </div>

                                    {s.tags && s.tags.length > 0 && (
                                        <div className="flex flex-wrap gap-1 mt-3">
                                            {s.tags.slice(0, 4).map(t => (
                                                <span key={t} className="text-[9px] bg-white border border-slate-200 text-slate-500 px-1.5 py-0.5 rounded shadow-sm">
                                                    #{t}
                                                </span>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            </div>
                        ))}
                    </div>
                )}

                {/* Footer */}
                <div className="mt-12 pt-6 border-t border-sky-200 flex justify-between items-center text-sky-800/50">
                    <span className="text-xs font-bold uppercase tracking-widest">Designed by 不咕鸟 CardGen</span>
                    <span className="text-xs font-mono">QQ: 442348584</span>
                </div>
            </div>
        </div>
    </div>
  );
};