import React, { useRef, useState } from 'react';
import { SessionData, ROOM_IDS, RoomId } from '../types';
import { format, startOfWeek, addDays, addWeeks, subWeeks, isSameWeek, endOfWeek } from 'date-fns';
import { zhCN } from 'date-fns/locale';
import { toPng } from 'html-to-image';
import { Copy, Check, Image as ImageIcon, Bomb, Pencil, FileJson, ChevronDown, ChevronUp, Users, ArrowRightLeft, History, ChevronLeft, ChevronRight, Calendar, UserPlus, LogOut } from 'lucide-react';
import { DataPanel } from './DataPanel';
import { useAuth } from '../contexts/AuthContext';
import { EnrollmentModal } from './EnrollmentModal';

interface ScheduleGridProps {
    sessions: SessionData[];
    satellites: SessionData[];
    onExplode: (id: string) => void;
    onEdit: (id: string) => void;
    onImport: (data: SessionData[]) => void;
    onCopyLastWeek: () => void;
    onEnroll?: (sessionId: string, action: 'enroll' | 'cancel') => void;
}

type ViewMode = 'date-rows' | 'room-rows';

export const ScheduleGrid: React.FC<ScheduleGridProps> = ({ sessions, satellites, onExplode, onEdit, onImport, onCopyLastWeek, onEnroll }) => {
    const { user } = useAuth();
    const scheduleRef = useRef<HTMLDivElement>(null);
    const [copied, setCopied] = useState(false);
    const [isGenerating, setIsGenerating] = useState(false);
    const [selectedId, setSelectedId] = useState<string | null>(null);
    const [viewMode, setViewMode] = useState<ViewMode>('date-rows');
    const [viewDate, setViewDate] = useState(new Date());

    // Data Management UI State
    const [showDataPanel, setShowDataPanel] = useState(false);

    // Enrollment UI State
    const [enrollingSession, setEnrollingSession] = useState<SessionData | null>(null);

    // Current week calculation based on viewDate
    const startOfSelectedWeek = startOfWeek(viewDate, { weekStartsOn: 1 });
    const endOfSelectedWeek = endOfWeek(viewDate, { weekStartsOn: 1 });
    const isCurrentWeek = isSameWeek(viewDate, new Date(), { weekStartsOn: 1 });

    const weekDays = Array.from({ length: 7 }).map((_, i) => {
        const date = addDays(startOfSelectedWeek, i);
        return {
            date,
            label: format(date, 'EEEE', { locale: zhCN }),
            shortLabel: format(date, 'EEE', { locale: zhCN }),
            fullDate: format(date, 'yyyy-MM-dd')
        };
    });

    const getSessions = (dateStr: string, roomId: RoomId) => {
        return sessions
            .filter(s => s.date === dateStr && s.roomId === roomId)
            .sort((a, b) => a.startTime.localeCompare(b.startTime));
    };

    // --- Navigation Handlers ---
    const handlePrevWeek = () => setViewDate(d => subWeeks(d, 1));
    const handleNextWeek = () => setViewDate(d => addWeeks(d, 1));
    const handleToday = () => setViewDate(new Date());

    // --- Export Helpers ---
    const handleCopyText = () => {
        const weekRangeStr = `${format(startOfSelectedWeek, 'MM/dd')} - ${format(endOfSelectedWeek, 'MM/dd')}`;
        let textOutput = `=== 成都秘密基地TRPG俱乐部 开团日程 (${weekRangeStr}) ===\n`;
        textOutput += `地点：文化宫地铁站D口前方，青羊区清江中路58号，本直体育联合中心2楼（羽毛球馆楼梯上）秘密基地TRPG俱乐部\n\n`;
        weekDays.forEach(day => {
            const daySessions = sessions.filter(s => s.date === day.fullDate && !s.isExploded);
            if (daySessions.length > 0) {
                textOutput += `【${day.label} ${format(day.date, 'MM/dd')}】\n`;
                daySessions.sort((a, b) => a.startTime.localeCompare(b.startTime));
                daySessions.forEach(s => {
                    // 格式：房间号（人数情况）——时间||模组名||规则||主持人（联系方式）
                    textOutput += `${s.roomId}（${s.currentPlayers}/${s.maxPlayers}）——${s.startTime}||${s.moduleName}||${s.ruleSystem}||${s.gmName}（${s.gmContact}）\n`;
                });
                textOutput += "\n";
            }
        });

        textOutput += "Generated by 不咕鸟 CardGen";
        navigator.clipboard.writeText(textOutput);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownloadImage = async () => {
        if (scheduleRef.current) {
            setSelectedId(null);
            setIsGenerating(true);
            try {
                await new Promise(r => setTimeout(r, 100)); // clear selection render
                const dataUrl = await toPng(scheduleRef.current, {
                    cacheBust: true,
                    pixelRatio: 2,
                    backgroundColor: '#ffffff',
                    fetchRequestInit: { mode: 'cors' }
                });
                const link = document.createElement('a');
                link.download = `trpg-schedule-${format(startOfSelectedWeek, 'yyyy-MM-dd')}.png`;
                link.href = dataUrl;
                link.click();
            } catch (err) {
                console.error(err);
                alert('生成图片失败，请重试');
            } finally {
                setIsGenerating(false);
            }
        }
    };

    const getTypeColor = (type: string) => {
        switch (type) {
            case '商团': return 'bg-amber-100 text-amber-700 border-amber-200';
            case '活动团': return 'bg-pink-100 text-pink-700 border-pink-200';
            default: return 'bg-indigo-50 text-indigo-700 border-indigo-200';
        }
    };

    // --- Render Helper for Session Card ---
    const renderSessionCard = (session: SessionData) => (
        <div
            key={session.id}
            onClick={(e) => { e.stopPropagation(); setSelectedId(selectedId === session.id ? null : session.id); }}
            className={`
            relative rounded-lg p-3 border transition-all cursor-pointer group shadow-sm text-left
            ${selectedId === session.id ? 'border-indigo-500 ring-2 ring-indigo-100 z-10 scale-[1.02] shadow-xl' : 'border-slate-200 hover:border-indigo-300 hover:shadow-md'}
            ${session.isExploded ? 'bg-slate-100 grayscale opacity-75' : 'bg-white'}
        `}
        >
            {/* Action Overlay */}
            {selectedId === session.id && (
                <div className="absolute -top-3 -right-3 flex gap-1 z-20 animate-in zoom-in duration-200">
                    <button
                        onClick={(e) => { e.stopPropagation(); onExplode(session.id); setSelectedId(null); }}
                        className={`w-8 h-8 rounded-full flex items-center justify-center text-white shadow-md border-2 border-white ${session.isExploded ? 'bg-slate-500' : 'bg-red-500 hover:bg-red-600'}`}
                    >
                        <Bomb size={14} />
                    </button>
                    <button
                        onClick={(e) => { e.stopPropagation(); onEdit(session.id); setSelectedId(null); }}
                        className="w-8 h-8 rounded-full bg-indigo-600 hover:bg-indigo-700 text-white flex items-center justify-center shadow-md border-2 border-white"
                    >
                        <Pencil size={14} />
                    </button>
                </div>
            )}

            {/* Top Row: Time, Type, Status */}
            <div className="flex justify-between items-start mb-2">
                <div className="flex items-center gap-1.5">
                    <span className={`text-xs font-mono font-bold px-1.5 py-0.5 rounded ${session.isExploded ? 'bg-slate-600 text-white line-through' : 'bg-slate-800 text-white'}`}>
                        {session.startTime}
                    </span>
                    <span className={`w-2 h-2 rounded-full ${session.status === '招募中' ? 'bg-green-500' :
                        session.status === '已满员' ? 'bg-red-500' :
                            session.status === '拼车中' ? 'bg-orange-500' :
                                session.status === '已结团' ? 'bg-gray-800' : 'bg-blue-500'
                        }`} />
                </div>
                <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded border ${getTypeColor(session.sessionType)}`}>
                    {session.sessionType}
                </span>
            </div>

            {/* Content */}
            <div className={session.isExploded ? 'line-through opacity-50' : ''}>
                <h4 className="font-bold text-slate-900 leading-tight text-sm mb-1">{session.moduleName}</h4>
                <div className="text-[10px] font-bold text-indigo-600 uppercase mb-2 truncate">{session.ruleSystem}</div>

                {/* Tags */}
                {session.tags && session.tags.length > 0 && (
                    <div className="flex flex-wrap gap-1 mb-2">
                        {session.tags.slice(0, 3).map(t => (
                            <span key={t} className="text-[9px] bg-slate-100 text-slate-500 px-1 rounded flex items-center">#{t}</span>
                        ))}
                    </div>
                )}
            </div>

            {/* Footer */}
            <div className={`mt-2 pt-2 border-t border-slate-100 flex justify-between items-center text-[10px] ${session.isExploded ? 'line-through text-slate-400' : 'text-slate-600'}`}>
                <div className="flex flex-col min-w-0 mr-1 flex-1">
                    <span className="font-bold truncate" title={session.gmName}>{session.gmName}</span>
                    <span className="text-[9px] text-slate-400 truncate" title={session.gmContact}>{session.gmContact}</span>
                </div>
                <div className="flex items-center gap-1 font-mono shrink-0">
                    <Users size={10} className="text-slate-400" />
                    <span className="font-bold text-slate-800">{session.currentPlayers}</span>
                    <span className="text-slate-400">/</span>
                    <span className="text-slate-400">{session.maxPlayers}</span>
                </div>
            </div>

            {/* Enrollment Action (Visible on hover or when recruiting) */}
            {session.status === '招募中' && !session.isExploded && (
                <div className="mt-2 text-center opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                    {user ? (
                        session.enrolledUsers?.some(u => u.userId === user.id) ? (
                            <button
                                onClick={(e) => { e.stopPropagation(); setEnrollingSession(session); }}
                                className="w-full bg-red-50 text-red-600 border border-red-200 py-1 rounded-md text-[10px] font-bold hover:bg-red-100 transition-colors flex items-center justify-center gap-1"
                            >
                                <LogOut size={12} /> 已报名 (点击取消)
                            </button>
                        ) : (
                            <button
                                onClick={(e) => { e.stopPropagation(); setEnrollingSession(session); }}
                                disabled={session.currentPlayers >= session.maxPlayers}
                                className="w-full bg-indigo-50 text-indigo-700 border border-indigo-200 py-1 rounded-md text-[10px] font-bold hover:bg-indigo-100 transition-colors flex items-center justify-center gap-1 disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                <UserPlus size={12} /> {session.currentPlayers >= session.maxPlayers ? '已满员' : '我要报名'}
                            </button>
                        )
                    ) : (
                        <div className="w-full bg-slate-50 text-slate-500 border border-slate-200 py-1 rounded-md text-[10px] font-bold">
                            请先登录以报名
                        </div>
                    )}
                </div>
            )}
        </div>
    );

    return (
        <div className="space-y-6 animate-in fade-in duration-500">
            {/* Toolbar */}
            <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-200 flex flex-wrap items-center justify-between gap-4 sticky top-20 z-30">
                {/* Left: Export Tools */}
                <div className="flex gap-3">
                    <button onClick={handleDownloadImage} disabled={isGenerating} className="btn-primary flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg font-bold hover:bg-indigo-700 transition shadow-sm disabled:opacity-50">
                        {isGenerating ? <span className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full" /> : <ImageIcon size={18} />}
                        下载长图
                    </button>
                    <button onClick={handleCopyText} className="flex items-center gap-2 px-4 py-2 bg-white text-slate-700 border border-slate-300 rounded-lg font-bold hover:bg-slate-50 transition shadow-sm">
                        {copied ? <Check size={18} className="text-green-500" /> : <Copy size={18} />}
                        {copied ? '已复制' : '复制文本'}
                    </button>
                </div>

                {/* Center: Week Navigation */}
                <div className="flex items-center bg-slate-100 rounded-lg p-1 shadow-inner border border-slate-200">
                    <button onClick={handlePrevWeek} className="p-2 hover:bg-white hover:shadow-sm rounded text-slate-500 hover:text-indigo-600 transition"><ChevronLeft size={18} /></button>
                    <div className="flex flex-col items-center px-4 w-36">
                        <span className="text-xs font-bold text-slate-400 uppercase leading-none mb-0.5">WEEK OF</span>
                        <span className="text-sm font-black font-mono text-slate-800 leading-none">
                            {format(startOfSelectedWeek, 'yyyy.MM.dd')}
                        </span>
                    </div>
                    <button onClick={handleNextWeek} className="p-2 hover:bg-white hover:shadow-sm rounded text-slate-500 hover:text-indigo-600 transition"><ChevronRight size={18} /></button>
                    {!isCurrentWeek && (
                        <button onClick={handleToday} className="ml-2 text-xs font-bold px-2 py-1 bg-white border border-slate-300 rounded text-slate-600 hover:text-indigo-600 hover:border-indigo-300">
                            回到本周
                        </button>
                    )}
                </div>

                {/* Right: View & Data */}
                <div className="flex gap-3">
                    <button onClick={onCopyLastWeek} className="flex items-center gap-2 px-3 py-2 bg-white text-indigo-700 border border-indigo-200 rounded-lg font-bold hover:bg-indigo-50 transition shadow-sm text-sm">
                        <History size={16} />
                        从上周复制
                    </button>
                    <button onClick={() => setViewMode(prev => prev === 'date-rows' ? 'room-rows' : 'date-rows')} className="flex items-center gap-2 px-3 py-2 bg-slate-100 text-slate-700 border border-slate-200 rounded-lg font-bold hover:bg-slate-200 transition shadow-sm text-sm">
                        <ArrowRightLeft size={16} />
                        {viewMode === 'date-rows' ? '转置' : '复原'}
                    </button>
                    <button onClick={() => setShowDataPanel(!showDataPanel)} className="flex items-center gap-2 text-slate-500 hover:text-slate-800 font-medium text-sm transition px-2">
                        <FileJson size={18} />
                        {showDataPanel ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                    </button>
                </div>
            </div>

            {/* Data Panel */}
            {showDataPanel && (
                <DataPanel
                    data={[...sessions, ...satellites]}
                    onImport={onImport}
                    onClose={() => setShowDataPanel(false)}
                />
            )}

            {/* Schedule Visualization */}
            <div className="overflow-x-auto pb-8 rounded-2xl border border-slate-200 bg-slate-100 shadow-inner">
                <div ref={scheduleRef} onClick={() => setSelectedId(null)} className="bg-white min-w-[2000px] inline-block shadow-xl pb-6">
                    {/* Header */}
                    <div className="bg-slate-900 text-white px-8 py-6 flex justify-between items-center border-b border-slate-800">
                        <div>
                            <h2 className="text-3xl font-black tracking-wider">成都秘密基地TRPG俱乐部</h2>
                            <div className="flex flex-col gap-1 mt-2">
                                <div className="flex items-center gap-4">
                                    <span className="bg-indigo-500 text-white text-xs font-bold px-2 py-0.5 rounded">WEEKLY SCHEDULE</span>
                                    <span className="text-slate-400 text-sm font-medium">开团日程表</span>
                                </div>
                                <div className="text-[10px] text-slate-500 font-bold opacity-80">
                                    地点：文化宫地铁站D口前方，青羊区清江中路58号，本直体育联合中心2楼（羽毛球馆楼梯上）秘密基地TRPG俱乐部
                                </div>
                            </div>
                        </div>
                        <div className="text-right">
                            <div className="text-3xl font-mono font-bold flex items-center gap-2 justify-end">
                                <Calendar size={28} className="text-slate-600" />
                                {format(startOfSelectedWeek, 'MM.dd')} - {format(endOfSelectedWeek, 'MM.dd')}
                            </div>
                            <div className="text-slate-500 font-bold text-sm tracking-widest">{format(startOfSelectedWeek, 'yyyy')}</div>
                        </div>
                    </div>

                    {viewMode === 'date-rows' ? (
                        // VIEW MODE 1: Rows = Dates, Cols = Rooms (Standard)
                        <>
                            {/* Grid Header (Rooms) */}
                            <div className={`grid grid-cols-[120px_repeat(${ROOM_IDS.length},1fr)] bg-slate-50 border-b border-slate-200`}>
                                <div className="p-4 flex items-center justify-center font-black text-slate-300 text-lg border-r border-slate-200">DATE</div>
                                {ROOM_IDS.map(room => (
                                    <div key={room} className="p-4 text-center border-r border-slate-200 last:border-r-0">
                                        <span className="block text-2xl font-black text-indigo-900">{room}</span>
                                        <span className="text-[10px] text-slate-400 uppercase font-bold">Room / Area</span>
                                    </div>
                                ))}
                            </div>

                            {/* Grid Body */}
                            {weekDays.map((day) => (
                                <div key={day.fullDate} className={`grid grid-cols-[120px_repeat(${ROOM_IDS.length},1fr)] border-b border-slate-200 last:border-b-0 min-h-[220px]`}>
                                    {/* Date Column */}
                                    <div className={`border-r border-slate-200 flex flex-col items-center justify-center p-4 ${day.fullDate === format(new Date(), 'yyyy-MM-dd') ? 'bg-indigo-50' : 'bg-slate-50'}`}>
                                        <span className={`text-2xl font-black ${day.fullDate === format(new Date(), 'yyyy-MM-dd') ? 'text-indigo-600' : 'text-slate-700'}`}>{day.shortLabel}</span>
                                        <span className="text-sm font-mono font-bold text-slate-400 mt-1">{format(day.date, 'MM/dd')}</span>
                                    </div>

                                    {/* Room Columns */}
                                    {ROOM_IDS.map(roomId => {
                                        const cellSessions = getSessions(day.fullDate, roomId);
                                        return (
                                            <div key={roomId} className="border-r border-slate-200 last:border-r-0 p-3 bg-white hover:bg-slate-50/50 transition-colors flex flex-col gap-3 relative">
                                                {cellSessions.map(renderSessionCard)}
                                            </div>
                                        );
                                    })}
                                </div>
                            ))}
                        </>
                    ) : (
                        // VIEW MODE 2: Rows = Rooms, Cols = Dates (Transposed)
                        <>
                            {/* Grid Header (Dates) */}
                            <div className="grid grid-cols-[120px_repeat(7,1fr)] bg-slate-50 border-b border-slate-200">
                                <div className="p-4 flex items-center justify-center font-black text-slate-300 text-lg border-r border-slate-200">ROOM</div>
                                {weekDays.map(day => (
                                    <div key={day.fullDate} className={`p-4 text-center border-r border-slate-200 last:border-r-0 ${day.fullDate === format(new Date(), 'yyyy-MM-dd') ? 'bg-indigo-50' : ''}`}>
                                        <span className={`block text-xl font-black ${day.fullDate === format(new Date(), 'yyyy-MM-dd') ? 'text-indigo-600' : 'text-indigo-900'}`}>{day.shortLabel}</span>
                                        <span className="text-[10px] text-slate-400 uppercase font-bold">{format(day.date, 'MM/dd')}</span>
                                    </div>
                                ))}
                            </div>

                            {/* Grid Body */}
                            {ROOM_IDS.map((roomId) => (
                                <div key={roomId} className="grid grid-cols-[120px_repeat(7,1fr)] border-b border-slate-200 last:border-b-0 min-h-[220px]">
                                    {/* Room Label Column */}
                                    <div className="bg-slate-50 border-r border-slate-200 flex flex-col items-center justify-center p-4">
                                        <span className="text-2xl font-black text-slate-700">{roomId}</span>
                                        <span className="text-[10px] text-slate-400 uppercase font-bold">Area</span>
                                    </div>

                                    {/* Date Columns */}
                                    {weekDays.map(day => {
                                        const cellSessions = getSessions(day.fullDate, roomId);
                                        return (
                                            <div key={day.fullDate} className="border-r border-slate-200 last:border-r-0 p-3 bg-white hover:bg-slate-50/50 transition-colors flex flex-col gap-3 relative">
                                                {cellSessions.map(renderSessionCard)}
                                            </div>
                                        );
                                    })}
                                </div>
                            ))}
                        </>
                    )}

                    {/* Footer */}
                    <div className="bg-slate-50 px-8 py-6 border-t border-slate-200 flex justify-between mt-8">
                        <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Designed by 不咕鸟 CardGen</span>
                        <span className="text-xs font-mono text-slate-400">QQ: 442348584 / WX: jeffyuyi</span>
                    </div>
                </div>
            </div>

            {/* Enrollment Modal */}
            {enrollingSession && user && onEnroll && (
                <EnrollmentModal
                    session={enrollingSession}
                    user={user}
                    isEnrolled={!!enrollingSession.enrolledUsers?.some(u => u.userId === user.id)}
                    onConfirm={() => {
                        const isEnrolled = !!enrollingSession.enrolledUsers?.some(u => u.userId === user.id);
                        onEnroll(enrollingSession.id, isEnrolled ? 'cancel' : 'enroll');
                        setEnrollingSession(null);
                        setSelectedId(null);
                    }}
                    onCancel={() => setEnrollingSession(null)}
                />
            )}
        </div>
    );
};