import React, { useRef, useState } from 'react';
import { SessionData } from '../types';
import { format, startOfWeek, addDays, addWeeks, subWeeks, isSameWeek, endOfWeek } from 'date-fns';
import { zhCN } from 'date-fns/locale';
import { toPng } from 'html-to-image';
import { Copy, Check, Image as ImageIcon, Bomb, Pencil, FileJson, ChevronDown, ChevronUp, Users, ChevronLeft, ChevronRight, Calendar, MapPin } from 'lucide-react';
import { DataPanel } from './DataPanel';

interface UniversityScheduleGridProps {
    sessions: SessionData[];
    onExplode: (id: string) => void;
    onEdit: (id: string) => void;
    onImport?: (data: SessionData[]) => void;
    canEdit?: boolean;
}

export const UniversityScheduleGrid: React.FC<UniversityScheduleGridProps> = ({ sessions, onExplode, onEdit, onImport, canEdit = true }) => {
    const scheduleRef = useRef<HTMLDivElement>(null);
    const [copied, setCopied] = useState(false);
    const [isGenerating, setIsGenerating] = useState(false);
    const [selectedId, setSelectedId] = useState<string | null>(null);
    const [viewDate, setViewDate] = useState(new Date());
    const [showDataPanel, setShowDataPanel] = useState(false);

    const startOfSelectedWeek = startOfWeek(viewDate, { weekStartsOn: 1 });
    const endOfSelectedWeek = endOfWeek(viewDate, { weekStartsOn: 1 });
    const isCurrentWeek = isSameWeek(viewDate, new Date(), { weekStartsOn: 1 });

    const weekDays = Array.from({ length: 7 }).map((_, i) => {
        const date = addDays(startOfSelectedWeek, i);
        return {
            date,
            label: format(date, 'EEEE', { locale: zhCN }),
            shortLabel: format(date, 'EEE', { locale: zhCN }),
            fullDate: format(date, 'yyyy-MM-dd')
        };
    });

    const getDaySessions = (dateStr: string) => {
        return sessions
            .filter(s => s.date === dateStr)
            .sort((a, b) => a.startTime.localeCompare(b.startTime));
    };

    const handlePrevWeek = () => setViewDate(d => subWeeks(d, 1));
    const handleNextWeek = () => setViewDate(d => addWeeks(d, 1));
    const handleToday = () => setViewDate(new Date());

    const handleCopyText = () => {
        const weekRangeStr = `${format(startOfSelectedWeek, 'MM/dd')} - ${format(endOfSelectedWeek, 'MM/dd')}`;
        let textOutput = `=== 成都高校面团公共约团日程 (${weekRangeStr}) ===\n\n`;

        weekDays.forEach(day => {
            const daySessions = sessions.filter(s => s.date === day.fullDate && !s.isExploded);
            if (daySessions.length > 0) {
                textOutput += `【${day.label} ${format(day.date, 'MM/dd')}】\n`;
                daySessions.sort((a, b) => a.startTime.localeCompare(b.startTime));
                daySessions.forEach(s => {
                    textOutput += `${s.startTime} || ${s.moduleName} || ${s.customLocation || '校内'} || ${s.gmName}\n`;
                });
                textOutput += "\n";
            }
        });

        textOutput += "Generated by 不咕鸟 CardGen";
        navigator.clipboard.writeText(textOutput);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownloadImage = async () => {
        if (scheduleRef.current) {
            setSelectedId(null);
            setIsGenerating(true);
            try {
                await new Promise(r => setTimeout(r, 100));
                const dataUrl = await toPng(scheduleRef.current, {
                    cacheBust: true,
                    pixelRatio: 2,
                    backgroundColor: '#ffffff',
                    fetchRequestInit: { mode: 'cors' }
                });
                const link = document.createElement('a');
                link.download = `university-schedule-${format(startOfSelectedWeek, 'yyyy-MM-dd')}.png`;
                link.href = dataUrl;
                link.click();
            } catch (err) {
                console.error(err);
                alert('生成图片失败，请重试');
            } finally {
                setIsGenerating(false);
            }
        }
    };

    const getTypeColor = (type: string) => {
        switch (type) {
            case '商团': return 'bg-amber-100 text-amber-700 border-amber-200';
            case '活动团': return 'bg-emerald-100 text-emerald-700 border-emerald-200';
            default: return 'bg-indigo-50 text-indigo-700 border-indigo-200';
        }
    };

    const renderSessionCard = (session: SessionData) => (
        <div
            key={session.id}
            onClick={(e) => { e.stopPropagation(); setSelectedId(selectedId === session.id ? null : session.id); }}
            className={`
                relative rounded-xl p-4 border transition-all cursor-pointer group shadow-sm text-left w-full
                ${selectedId === session.id ? 'border-indigo-500 ring-2 ring-indigo-100 z-10 scale-[1.01] shadow-lg' : 'border-slate-200 hover:border-indigo-300 hover:shadow-md'}
                ${session.isExploded ? 'bg-slate-50 grayscale opacity-75' : 'bg-white'}
            `}
        >
            {selectedId === session.id && canEdit && (
                <div className="absolute -top-3 -right-3 flex gap-1 z-20 animate-in zoom-in duration-200">
                    <button
                        onClick={(e) => { e.stopPropagation(); onExplode(session.id); setSelectedId(null); }}
                        className={`w-8 h-8 rounded-full flex items-center justify-center text-white shadow-md border-2 border-white ${session.isExploded ? 'bg-slate-500' : 'bg-red-500 hover:bg-red-600'}`}
                    >
                        <Bomb size={14} />
                    </button>
                    <button
                        onClick={(e) => { e.stopPropagation(); onEdit(session.id); setSelectedId(null); }}
                        className="w-8 h-8 rounded-full bg-indigo-600 hover:bg-indigo-700 text-white flex items-center justify-center shadow-md border-2 border-white"
                    >
                        <Pencil size={14} />
                    </button>
                </div>
            )}

            <div className="flex justify-between items-start mb-2">
                <span className={`text-xs font-mono font-bold px-2 py-0.5 rounded ${session.isExploded ? 'bg-slate-600 text-white line-through' : 'bg-slate-800 text-white'}`}>
                    {session.startTime}
                </span>
                <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded border ${getTypeColor(session.sessionType)}`}>
                    {session.sessionType}
                </span>
            </div>

            <div className={session.isExploded ? 'line-through opacity-50' : ''}>
                <h4 className="font-bold text-slate-900 leading-tight text-base mb-1">{session.moduleName}</h4>
                <div className="text-[10px] font-bold text-indigo-600 uppercase mb-3">{session.ruleSystem}</div>

                <div className="flex items-center gap-1.5 text-slate-500 mb-3 bg-slate-50 p-2 rounded-lg border border-slate-100">
                    <MapPin size={12} className="shrink-0 text-slate-400" />
                    <span className="text-[11px] font-medium leading-tight truncate">{session.customLocation || '校内待定'}</span>
                </div>
            </div>

            <div className={`pt-2 border-t border-slate-100 flex justify-between items-center text-[10px] ${session.isExploded ? 'text-slate-400' : 'text-slate-600'}`}>
                <div className="flex flex-col min-w-0 mr-1 flex-1">
                    <span className="font-bold truncate">{session.gmName}</span>
                    <span className="text-[9px] text-slate-400 truncate">{session.gmContact}</span>
                </div>
                <div className="flex items-center gap-1 font-mono shrink-0">
                    <Users size={10} className="text-slate-400" />
                    <span className="font-bold text-slate-800">{session.currentPlayers}/{session.maxPlayers}</span>
                </div>
            </div>
        </div>
    );

    return (
        <div className="space-y-6 animate-in fade-in duration-500">
            <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-200 flex flex-wrap items-center justify-between gap-4 sticky top-20 z-30">
                <div className="flex gap-3">
                    <button onClick={handleDownloadImage} disabled={isGenerating} className="flex items-center gap-2 px-4 py-2 bg-emerald-600 text-white rounded-lg font-bold hover:bg-emerald-700 transition shadow-sm disabled:opacity-50">
                        {isGenerating ? <span className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full" /> : <ImageIcon size={18} />}
                        下载日程图
                    </button>
                    <button onClick={handleCopyText} className="flex items-center gap-2 px-4 py-2 bg-white text-slate-700 border border-slate-300 rounded-lg font-bold hover:bg-slate-50 transition shadow-sm">
                        {copied ? <Check size={18} className="text-green-500" /> : <Copy size={18} />}
                        {copied ? '已复制文本' : '复制群公告'}
                    </button>
                </div>

                <div className="flex items-center bg-slate-100 rounded-lg p-1 border border-slate-200">
                    <button onClick={handlePrevWeek} className="p-2 hover:bg-white hover:shadow-sm rounded text-slate-500 transition"><ChevronLeft size={18} /></button>
                    <div className="flex flex-col items-center px-6 w-40">
                        <span className="text-[10px] font-bold text-slate-400 uppercase tracking-tighter">UNIVERSITY WEEK</span>
                        <span className="text-sm font-black font-mono text-slate-800">
                            {format(startOfSelectedWeek, 'MM.dd')} - {format(endOfSelectedWeek, 'MM.dd')}
                        </span>
                    </div>
                    <button onClick={handleNextWeek} className="p-2 hover:bg-white hover:shadow-sm rounded text-slate-500 transition"><ChevronRight size={18} /></button>
                </div>

                <div className="flex gap-2">
                    {!isCurrentWeek && (
                        <button onClick={handleToday} className="text-xs font-bold px-3 py-2 bg-white border border-slate-300 rounded-lg text-slate-600 hover:text-emerald-600">回到本周</button>
                    )}
                    <button onClick={() => setShowDataPanel(!showDataPanel)} className="flex items-center gap-2 text-slate-400 hover:text-slate-600 p-2">
                        <FileJson size={20} />
                        {showDataPanel ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                    </button>
                </div>
            </div>

            {showDataPanel && (
                <DataPanel
                    data={sessions}
                    onImport={onImport}
                    onClose={() => setShowDataPanel(false)}
                />
            )}

            <div className="overflow-x-auto pb-4">
                <div ref={scheduleRef} className="bg-white min-w-[1200px] shadow-xl rounded-2xl border border-slate-200 overflow-hidden">
                    <div className="bg-emerald-900 text-white px-8 py-8 flex flex-col gap-5">
                        <div className="flex justify-between items-start">
                            <div>
                                <h2 className="text-3xl font-black tracking-tight flex items-center gap-3">
                                    <span className="p-2 bg-white text-emerald-900 rounded-lg"><Calendar size={24} /></span>
                                    成都高校面团公共约团页面
                                </h2>
                                <p className="text-emerald-400 text-sm font-bold mt-2 tracking-widest uppercase">Chengdu University TRPG Community Schedule</p>
                            </div>
                            <div className="text-right mt-1">
                                <div className="text-sm font-bold text-emerald-500 uppercase">Season 2024</div>
                                <div className="text-2xl font-black font-mono">{format(startOfSelectedWeek, 'yyyy')}</div>
                            </div>
                        </div>
                        <div className="bg-emerald-950/50 p-3 rounded text-[10px] text-emerald-200/80 leading-relaxed border border-emerald-800/50">
                            免责声明：本页面系成都秘密基地TRPG俱乐部为支持各大高校TRPG社群而无偿提供的公共信息发布平台。俱乐部不对本平台中由任何主持人、参与者及活动场地之间产生的任何经济纠纷或意外损失承担法律责任。请各位玩家自行甄别活动信息，注意人身及财产安全。
                        </div>
                    </div>

                    <div className="grid grid-cols-7 bg-slate-50 border-b border-slate-200">
                        {weekDays.map(day => (
                            <div key={day.fullDate} className={`p-4 text-center border-r border-slate-200 last:border-r-0 ${day.fullDate === format(new Date(), 'yyyy-MM-dd') ? 'bg-emerald-50' : ''}`}>
                                <span className={`block text-xl font-black ${day.fullDate === format(new Date(), 'yyyy-MM-dd') ? 'text-emerald-600' : 'text-slate-900'}`}>{day.label}</span>
                                <span className="text-[10px] text-slate-400 font-bold">{format(day.date, 'MM月dd日')}</span>
                            </div>
                        ))}
                    </div>

                    <div className="grid grid-cols-7 min-h-[500px]">
                        {weekDays.map(day => {
                            const daySessions = getDaySessions(day.fullDate);
                            return (
                                <div key={day.fullDate} className={`border-r border-slate-200 last:border-r-0 p-3 flex flex-col gap-4 ${day.fullDate === format(new Date(), 'yyyy-MM-dd') ? 'bg-emerald-50/20' : ''}`}>
                                    {daySessions.map(renderSessionCard)}
                                    {daySessions.length === 0 && (
                                        <div className="flex-1 flex items-center justify-center opacity-10 py-20 grayscale">
                                            <MapPin size={48} />
                                        </div>
                                    )}
                                </div>
                            );
                        })}
                    </div>

                    <div className="bg-slate-50 px-8 py-6 border-t border-slate-200 flex justify-between">
                        <span className="text-xs font-bold text-slate-400 uppercase tracking-widest italic flex items-center gap-2">
                            <Check size={14} /> Verified by Chengdu University Community
                        </span>
                        <span className="text-xs font-mono text-slate-400">CardGen v4.0.0</span>
                    </div>
                </div>
            </div>
        </div>
    );
};
